### ISSUE TITLE
How to build from source on MSYS2 MINGW64?

### ISSUE THREAD

**Issue by iahung** [GlistEngine/GlistEngine#500]

**Comment by kayraurfali** [comment]
Refer to: https://github.com/GlistEngine/GlistEngine#ii-installation-for-developers

Stick with the installation steps that are under 'On Windows' headings. Following the installation, when you clone the relative [GlistEngine/glistzbin-win64](https://github.com/GlistEngine/glistzbin-win64) repo, you should be good to go assuming you are still following the installation guide at that point. Otherwise, you have to change:
https://github.com/GlistEngine/GlistEngine/blob/ae1567ac6bbd5ce3e0b981d81c619e446f0f2932/engine/CMakeLists.txt#L59
to your relative MinGW directory.

Altought I recommend you use the provided binaries from [GlistEngine/glistzbin-win64](https://github.com/GlistEngine/glistzbin-win64). Since there is also binaries for our preferred development IDE, eclipse, and also the vendor binaries that we link against the GlistEngine.

**Comment by kayraurfali** [comment]
> Refer to: https://github.com/GlistEngine/GlistEngine#ii-installation-for-developers
> 
> Stick with the installation steps that are under 'On Windows' headings. Following the installation, when you clone the relative [GlistEngine/glistzbin-win64](https://github.com/GlistEngine/glistzbin-win64) repo, you should be good to go assuming you are still following the installation guide at that point. Otherwise, you have to change:
> 
> https://github.com/GlistEngine/GlistEngine/blob/ae1567ac6bbd5ce3e0b981d81c619e446f0f2932/engine/CMakeLists.txt#L59
> 
> 
> to your relative MinGW directory.
> Altought I recommend you use the provided binaries from [GlistEngine/glistzbin-win64](https://github.com/GlistEngine/glistzbin-win64). Since there is also binaries for our preferred development IDE, eclipse, and also the vendor binaries that we link against the GlistEngine.

On a quick note, don't forget that you have to put `C:/msys2/clang64` if you have downloaded the necessary binaries for clang and `C:/msys2/mingw64` if you downloaded binaries for gcc
