### ISSUE TITLE
Cmake erorr

### ISSUE THREAD

**Issue by C04dy** [GlistEngine/GlistEngine#790]
i don't use cmake normally and this engine gives me these errors i even do that unresolved Inclusions thing and still get these errors im an old student of yours and i dont remember getting thse errors

![image](https://github.com/GlistEngine/GlistEngine/assets/101457058/e14940e4-b35c-4182-bab9-0f36454f984b)

**Comment by noyanc** [comment]
Hello, if you've cloned the new version of the engine, you don't need to mind these warning. These are false errors. We don't use g++ anymore, but we use clang. You can contact me via Discord for help if you are are an old student of us.

**Comment by C04dy** [comment]
i left after the first course that about making a 2D game because of some stuff i cant explain so we never met i don't know your discord nickname

**Comment by noyanc** [comment]
Ok no problem, if you have the old installation, many things changed since then.

Can you please delete or rename your old ~/dev/glist folder and reclone the project from Github?

Or instead of cloning, you can use our new installer as well. You can download it from [GlistEngine Windows installer](https://glistengine.com/downloads/GlistEngine-setup.exe
)

Or you can contact us via our Whatsapp number. We provide installation support for our students.

**Comment by C04dy** [comment]
i already do those and thats when i get erorrs but i think thats erorr because of cmake? idk anyways thank you if you want to contact me in any form heres my discord: codyea
